#!/bin/bash

. /etc/linuxmuster-wikidoku/wikidoku.conf

AUSGABE="wikidoc[[loglist|Kommandologs]]\n"

AUSGABE="${AUSGABE}~~NOCACHE~~\n\n"
AUSGABE="${AUSGABE}===== Kommandologs =====\n\n"
AUSGABE="${AUSGABE}{{simplefilelist>${COMMANDLOGS}:*}}\n"

echo -e $AUSGABE
