#!/bin/bash
. /etc/linuxmuster-wikidoku/wikidoku.conf
LOGALLCMD_WIKIPATH="/home/linuxmuster-portfolio/data/media/restricted/schulnetzbetreuung/commandlogs"
LOGALLCMD_LOGDATE=`date +'%b %d %H:%M:%S:'`
LOGALLCMD_FILENAME=$LOGALLCMD_WIKIPATH/`date +'%Y%m%d'`.txt
export PROMPT_COMMAND='echo -e "`date +'%Y%m%d-%H:%M:%S'`\t"$USER "\tCOMMAND: " "$(history 1 | cut -c8-)" >> $LOGALLCMD_FILENAME'
export PS1="(wikilog) $PS1 "
